table Fact_Sales
	lineageTag: 90c031f3-cd1c-46cd-964a-4b526ea8714b

	measure 'Total Sales' =
			
			SUM(Fact_Sales[sales_amount])
		lineageTag: 5eca5455-a3bd-4a53-9a82-95f5bbdc96c8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Quantity' =
			
			SUM(Fact_Sales[quantity])
		formatString: 0
		lineageTag: 392a8381-52a9-4e4b-b80d-c781b6fcc899

	measure 'MoM Growth %' =
			
			VAR CurrentSales =
			    [Total Sales]
			
			VAR PreviousMonthSales =
			    CALCULATE(
			        [Total Sales],
			        DATEADD(Dim_Date[Date], -1, MONTH)
			    )
			
			RETURN
			    DIVIDE(
			        CurrentSales - PreviousMonthSales,
			        PreviousMonthSales,
			        0
			    )
		lineageTag: ac2b5679-9af4-4966-9567-8572f854852c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Running Total Sales' =
			
			CALCULATE(
			    [Total Sales],
			    FILTER(
			        ALLSELECTED(Dim_Date[Date]),
			        Dim_Date[Date] <= MAX(Dim_Date[Date])
			    )
			)
		lineageTag: da3194d7-e34b-4a03-965f-1b540dc34a0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Item Sales Rank' =
			
			RANKX(
			    ALLSELECTED(Dim_Product[item]),
			    [Total Sales],
			    ,
			    DESC,
			    DENSE
			)
		formatString: 0
		lineageTag: 69ac8c28-b98a-493d-8fd9-449dbda4ea8d

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 32dcbd65-06f3-4103-9760-eccf27529c60
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 085657f6-8f6f-45d8-9291-7b656dc6844a
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: 64f3e740-ff07-4e41-99ce-8496aba52686
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 6439f8d1-5d24-449b-a05b-567be8479d26
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: a1a8cc14-fe03-4e0b-9897-9a5b800cd196
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 0d8b1011-8de1-4a2c-b06c-832c858a8820
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 696aa110-0066-414f-98b2-0be49c17f789
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Source_Sales,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"sale_id", "category"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

