table Source_Sales
	lineageTag: a21006b9-25ac-4ecf-a28c-5464546fb84b

	column sale_id
		dataType: int64
		formatString: 0
		lineageTag: a1cb92fc-8191-42ec-a352-8ab67d39b864
		summarizeBy: sum
		sourceColumn: sale_id

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e51c45c-36ec-4ed6-8771-ba16246a86c6
		summarizeBy: none
		sourceColumn: date

		variation Variation
			isDefault
			relationship: d4a7f242-26e7-4c65-b248-08f9e93b190f
			defaultHierarchy: LocalDateTable_ff7e4424-fef1-42b1-84ce-3da6cbd66ed1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column city
		dataType: string
		lineageTag: 41e3dcc6-7d1a-4378-be1f-e4825c0acfd2
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column store_format
		dataType: string
		lineageTag: b2a642ef-2e0e-4159-92f6-6fb0c4cd50b1
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: bb416c4c-2aba-4fb0-8cea-fc79c0941b4b
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column item
		dataType: string
		lineageTag: 88bec6ae-a3a2-4063-9888-2f281679b022
		summarizeBy: none
		sourceColumn: item

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		formatString: 0
		lineageTag: 7eab11b8-1e15-4fce-bcbc-b3aa327fe98d
		summarizeBy: sum
		sourceColumn: quantity

		annotation SummarizationSetBy = Automatic

	column unit_price
		dataType: int64
		formatString: 0
		lineageTag: 398979b6-aac8-40bb-bc00-98a2646b270e
		summarizeBy: sum
		sourceColumn: unit_price

		annotation SummarizationSetBy = Automatic

	column sales_amount
		dataType: double
		lineageTag: 086ff49e-f246-4214-8a64-2383ef61c9a1
		summarizeBy: sum
		sourceColumn: sales_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Source_Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\HP\Downloads\brewmetrics_sales.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

